 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author Galen
 */
public enum CourseSiteGeneratorPropertyType {
    CSG_FULL_WINDOW,
    CSG_TABS,
    
    CSG_EVERYTHING_PANE,
    //FIRST
    CSG_SITE_PANE,
    CSG_BANNER_PANE,
    CSG_BANNER_HEADER,
    CSG_SUBJECT_COMBO_BOX,
    CSG_NUMBER_COMBO_BOX,
    CSG_SEMESTER_COMBO_BOX,
    CSG_YEAR_COMBO_BOX,
    CSG_TITLE_TEXT_FIELD,
    CSG_EXPORT_DIR_LINK,
    
    CSG_SUBJECT_LABEL,
    CSG_NUMBER_LABEL,
    CSG_SEMESTER_LABEL,
    CSG_YEAR_LABEL,
    
    CSG_TITLE_LABEL,
    CSG_EXPORT_DIR_LABEL,
    
    CSG_PAGES_PANE,
    CSG_PAGES_HEADER,
    CSG_HOME_CHECK_BOX,
    CSG_SYLLABUS_CHECK_BOX,
    CSG_SCHEDULE_CHECK_BOX,
    CSG_HOMEWORK_CHECK_BOX,
    
    CSG_PAGES_HOME_LABEL,
    CSG_PAGES_SYLLABUS_LABEL,
    CSG_PAGES_SCHEDULE_LABEL,
    CSG_PAGES_HOMEWORK_LABEL,
    
    
    CSG_STYLE_PANE,
    CSG_TEST_IMAGE_VIEW,
    
    
    
    CSG_STYLE_HEADER,
    
    CSG_FAVICON_ICON_BUTTON,
    CSG_NAVBAR_ICON_BUTTON,
    CSG_LEFT_FOOTER_ICON_BUTTON,
    CSG_RIGHT_FOOTER_ICON_BUTTON,
    CSG_FAVICON_ICON,
    CSG_NAVBAR_ICON,
    CSG_LEFT_FOOTER_IMAGE_ICON,
    CSG_RIGHT_FOOTER_IMAGE_ICON,
    CSG_FAC_SS_COMBO_BOX,
    CSG_STYLE_NOTE,
    CSG_FONTS_AND_COLORS_LABEL,
    CSG_FONTS_AND_COLORS_COMBO_BOX,
    
    CSG_INSTRUCTOR_PANE,
    CSG_INSTRUCTOR_HEADER,
    CSG_INSTRUCTOR_NAME_TEXT_FIELD,
    CSG_INSTRUCTOR_NAME_TEXT_FIELD_HEADER,
    CSG_INSTRUCTOR_ROOM_TEXT_FIELD,
    CSG_INSTRUCTOR_ROOM_TEXT_FIELD_HEADER,
    CSG_INSTRUCTOR_EMAIL_TEXT_FIELD,
    CSG_INSTRUCTOR_EMAIL_TEXT_FIELD_HEADER,
    CSG_INSTRUCTOR_HOME_PAGE_TEXT_FIELD,
    CSG_INSTRUCTOR_HOME_PAGE_TEXT_FIELD_HEADER,
    
    CSG_OFFICE_HOURS_EXPAND_BUTTON,
    CSG_INSTRUCTOR_OFFICE_HOURS,
    CSG_INSTRUCTOR_OFFICE_HOURS_BOX,
    CSG_OFFICE_HOURS_DAY_TEXT,
    
    CSG_FOOLPROOF_SETTINGS,
    
    //SECOND
    CSG_SYLLABUS_PANE,
    CSG_DESCRIPTION_PANE,
    CSG_DESCRIPTION_HEADER,
    CSG_TOPICS_PANE,
    CSG_TOPICS_HEADER,
    CSG_PREREQUISITES_PANE,
    CSG_PREREQUISITES_HEADER,
    CSG_OUTCOMES_PANE,
    CSG_OUTCOMES_HEADER,
    CSG_TEXTBOOKS_PANE,
    CSG_TEXTBOOKS_HEADER,
    CSG_GRADED_COMPONENTS_PANE,
    CSG_GRADED_COMPONENTS_HEADER,
    CSG_GRADING_NOTE_PANE,
    CSG_GRADING_NOTE_HEADER,
    CSG_ACADEMIC_DISHONESTY_PANE,
    CSG_ACADEMIC_DISHONESTY_HEADER,
    CSG_SPECIAL_ASSISTANCE_PANE,
    CSG_SPECIAL_ASSISTANCE_HEADER,
    
    CSG_DESCRIPTION_TEXT_AREA,
    CSG_TOPICS_TEXT_AREA,
    CSG_PREREQUISITES_TEXT_AREA,
    CSG_OUTCOMES_TEXT_AREA,
    CSG_TEXTBOOKS_TEXT_AREA,
    CSG_GRADED_COMPONENTS_TEXT_AREA,
    CSG_GRADING_NOTE_TEXT_AREA,
    CSG_ACADEMIC_DISHONESTY_TEXT_AREA,
    CSG_SPECIAL_ASSISTANCE_TEXT_AREA,
    
    //THIRD
    CSG_MEETING_TIMES_PANE,
    
    CSG_LECTURES_PANE,
    CSG_INLECTUREST,
    CSG_LECTURES_H_BOX,
    CSG_LECTURES_HEADER,
    CSG_ADD_LECTURE_BUTTON,
    CSG_REMOVE_LECTURE_BUTTON,
    
    CSG_INRECITATIONST,
    CSG_RECITATIONS_H_BOX,
    CSG_RECITATIONS_PANE,
    CSG_RECITATIONS_HEADER,
    CSG_ADD_RECITATION_BUTTON,
    CSG_REMOVE_RECITATION_BUTTON,
    
    CSG_INLABST,
    CSG_LABS_H_BOX,
    CSG_LABS_PANE,
    CSG_LABS_HEADER,
    CSG_ADD_LAB_BUTTON,
    CSG_REMOVE_LAB_BUTTON,
    
    
    CSG_LECTURES_TABLE_VIEW,
    CSG_RECITATIONS_TABLE_VIEW,
    CSG_LABS_TABLE_VIEW,
    
    CSG_esSECTION_TABLE_COLUMN,
    CSG_DAYS_TABLE_COLUMN,
    CSG_TIME_TABLE_COLUMN,
    CSG_ROOM_TABLE_COLUMN,
    
    CSG_RSECTION_TABLE_COLUMN,
    CSG_RDAYS_TIME_TABLE_COLUMN,
    CSG_RROOM_TABLE_COLUMN,
    CSG_RTA1_TABLE_COLUMN,
    CSG_RTA2_TABLE_COLUMN,
    
    CSG_LSECTION_TABLE_COLUMN,
    CSG_LDAYS_TIME_TABLE_COLUMN,
    CSG_LROOM_TABLE_COLUMN,
    CSG_LTA1_TABLE_COLUMN,
    CSG_LTA2_TABLE_COLUMN,
    
    
    //FOURTH
    CSG_OFFICE_HOURS_PANE,
    CSG_TAS_PANE,
    CSG_TAS,
    CSG_TAs_HEADER,
    CSG_REMOVE_TA_BUTTON,
    CSG_ALL_RADIO_BUTTON,
    CSG_GRADUATE_RADIO_BUTTON,
    CSG_UNDERGRADUATE_RADIO_BUTTON,
    CSG_TAS_TABLE_VIEW,
    
    CSG_TA_NAME_TABLE_COLUMN,
    CSG_TA_EMAIL_TABLE_COLUMN,
    CSG_TA_TIME_SLOTS_TABLE_COLUMN,
    CSG_TA_TYPE_TABLE_COLUMN,
    
    CSG_ADD_TA_PANE,
    CSG_TA_NAME_TEXT_FIELD,
    CSG_TA_EMAIL_TEXT_FIELD,
    CSG_ADD_TA_BUTTON,
    
    CSG_OFFICE_HOURS_TABLE_PANE,
    
    CSG_OFFICE_HOURS_HEADER,
    CSG_OFFICE_HOURS_START_TIME_LABEL,
    CSG_OFFICE_HOURS_START_TIME_COMBO_BOX,
    CSG_OFFICE_HOURS_END_TIME_LABEL,
    CSG_OFFICE_HOURS_END_TIME_COMBO_BOX,
    
    CSG_OFFICE_HOURS_TABLE_VIEW,
    CSG_START_TIME_TABLE_COLUMN,
    CSG_END_TIME_TABLE_COLUMN,
    CSG_MONDAY_TABLE_COLUMN,
    CSG_TUESDAY_TABLE_COLUMN,
    CSG_WEDNESDAY_TABLE_COLUMN,
    CSG_THURSDAY_TABLE_COLUMN,
    CSG_FRIDAY_TABLE_COLUMN,
    CSG_DAYS_OF_WEEK,
    
    CSG_EDIT_TA_DIALOG,
    CSG_EDIT_NAME_TEXT_FIELD,
    CSG_EDIT_EMAIL_TEXT_FIELD,
    CSG_EDIT_TYPE_GRADUATE_BUTTON,
    CSG_EDIT_TYPE_UNDERGRADUATE_BUTTON,
    CSG_EDIT_OK_BUTTON,
    CSG_EDIT_CANCEL_BUTTON,
    
    //FIFTH
    CSG_SCHEDULE_PANE,
    CSG_CALENDAR_BOUNDARIES_PANE,
    CSG_CALENDAR_BOUNDARIES_HEADER,
    CSG_CALENDAR_BOUNDARIES_START_DAY,
    CSG_CALENDAR_BOUNDARIES_END_DAY,
    
    CSG_ADD_EDIT_HEADER,
    CSG_STARTING_DATE_PICKER,
    CSG_ENDING_DATE_PICKER,
    CSG_SCHEDULE_ITEMS_PANE,
    CSG_DELETE_SCHEDULE_ITEM_BUTTON,
    CSG_SCHEDULE_ITEMS_HEADER,
    CSG_SCHEDULE_ITEMS_TABLE_VIEW,
    CSG_TYPE_TABLE_COLUMN,
    CSG_DATE_TABLE_COLUMN,
    CSG_TITLE_TABLE_COLUMN,
    CSG_TOPIC_TABLE_COLUMN,
    CSG_ADD_EDIT_PANE,
    
    CSG_ADD_EDIT_TYPE_PANE,
    CSG_ADD_EDIT_DATE_PANE,
    CSG_ADD_EDIT_TITLE_PANE,
    CSG_ADD_EDIT_TOPIC_PANE,
    CSG_ADD_EDIT_LINK_PANE,
    
    CSG_ADD_EDIT_TYPE_HEADER,
    CSG_ADD_EDIT_TYPE_COMBO_BOX,
    CSG_ADD_EDIT_DATE_HEADER,
    CSG_ADD_EDIT_DATE_DATE_PICKER,
    CSG_ADD_EDIT_TITLE_HEADER,
    CSG_ADD_EDIT_TITLE_TEXT_FIELD,
    CSG_ADD_EDIT_TOPIC_HEADER,
    CSG_ADD_EDIT_TOPIC_TEXT_FIELD,
    CSG_ADD_EDIT_LINK_HEADER,
    CSG_ADD_EDIT_LINK_TEXT_FIELD,
    
    CSG_ADD_EDIT_TWO_BUTTONS_PANE,
    CSG_ADD_EDIT_UPDATE_BUTTON,
    CSG_ADD_EDIT_CLEAR_BUTTON,
    
    //Dialogs
    //Tab3
    CSG_NO_LECTURE_SELECTED_TITLE,
    CSG_NO_LECTURE_SELECTED_CONTENT,
    CSG_NO_RECITATION_SELECTED_TITLE,
    CSG_NO_RECITATION_SELECTED_CONTENT,
    CSG_NO_LAB_SELECTED_TITLE,
    CSG_NO_LAB_SELECTED_CONTENT,
    
    //Tab4
    CSG_NO_TA_SELECTED_TITLE,
    CSG_NO_TA_SELECTED_CONTENT,
    
    //Tab5 
    CSG_NO_SCHEDULE_ITEM_SELECTED_TITLE,
    CSG_NO_SCHEDULE_ITEM_SELECTED_CONTENT,
    
    
    //OPTIONS LISTS
    GLOBAL_SUBJECT_OPTIONS,
    GLOBAL_NUMBER_OPTIONS,
    GLOBAL_SEMESTER_OPTIONS,
    FIRST_SUBJECT,
    FIRST_NUMBER,
    FIRST_SEMESTER,
    DEFAULT_START_TIME,
    DEFAULT_END_TIME,
    START_TIME_OPTIONS,
    END_TIME_OPTIONS
    
}
